default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/tumbleweed_gdax_development

test:
  <<: *default
  database: db/tumbleweed_gdax_test

# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: db/tumbleweed_gdax_production
  username: <%= ENV['TUMBLEWEED_GDAX_DB_USER'] %>
  password: <%= ENV['TUMBLEWEED_GDAX_DB_PASSWORD'] %>
